### ISSUE TITLE
error produced by add.py

### ISSUE THREAD

**Issue by nagoue** [genouest/biomaj2galaxy#2]
Hi,

I got the following error running biomaj2galaxy : 

>   File "/storage/galaxydev/biomaj/venv/lib/python2.7/site-packages/biomaj2galaxy/commands/add.py", line 204, in add
>  ctx.gi.tool_data.delete_data_table('__dbkeys__', "\t".join(dbkey_entry))
> TypeError: can only join an iterable

that is produced on one new genome otherwise it is working well with previous genomes until we moved to galaxy 19.05.

This is solved by adding a conditional code before the for loop :

`

    if not need_dbkey:

        for c in table_counts.keys():

            need_dbkey = 'dbkey' in tables_format[c]
        
            if need_dbkey:

                break
`

This modification doesn't break on other genomes. 
However, I am not sure to understand how the code is behaving and why the error "appears" for that genome only and not the others... 
I would be pleased to hear if you have some explanation.
Cheers,

**Comment by abretaud** [comment]
Salut Nadia!
Which version of biomaj2galaxy did you use? I've made some fixes in the master branch for the latest galaxy versions, which I haven't released yet (just forgot!).

**Comment by nagoue** [comment]
Hello Anthony,
I am using biomaj2galaxy version 2.0.1. Should I wait next update ?
Thanks

**Comment by abretaud** [comment]
I'll make a new release, just checking if everything's ready
You'll need to update the data managers in galaxy too

**Comment by nagoue** [comment]
alright :+1:

**Comment by abretaud** [comment]
Ok... I've tried to release a 2.1.0, but tests are failing currently, as the 19.09 docker image is not yet ready. Which means the release wouldn't be pushed to pypi. So it'll wait 2020 :(
In the meantime, you can try to use the code from the master branch like this: `pip install git+https://github.com/genouest/biomaj2galaxy.git`
Also, updating to 19.09 would be good if you haven't done yet, there was several problems with data managers in 19.05, and I'm not sure they all got fixed.

**Comment by nagoue** [comment]
So I installed 19.09 and biomaj2galaxy as recommended.
Biomaj and biomaj2galaxy went without error however the loc files in data_manager_manual are not updated (data_manager_fetch_genome_dbkeys_all_fasta loc files are updated).
Nothing special from galaxy.log ...
Would you have some suggestions ?

**Comment by abretaud** [comment]
Hum, restart galaxy and retry? :(
Even if the loc files are empty, do you see anything interesting in https://you-galaxy-url/admin/data_manager/ ? At least the tables you're trying to fill should appear there

**Comment by nagoue** [comment]
It seems like it was a problem with 2 versions of data_manager_manual. I had to uninstall  the two versions of data manager, remove folders still in place and install again the latest version of data_manager_manual.
To conclude, the biomaj2galaxy.git is working as expected with galaxy19.09
Good luck with the tests !
Many thanks for your great job

**Comment by abretaud** [comment]
Ah cool that you found a solution!
Sorry I had not much time to help more :/
The docker image for galaxy 19.09 should be ready soon, so the biomaj2galaxy release should come after that

**Comment by abretaud** [comment]
Hi @nagoue 
The 2.1.0 version is finally out now : https://pypi.org/project/biomaj2galaxy/2.1.0/
Cheers

**Comment by nagoue** [comment]
Bonjour ! 

Thank you for the update. 
Cheers 


De: "Anthony Bretaudeau" <notifications@github.com> 
À: "genouest/biomaj2galaxy" <biomaj2galaxy@noreply.github.com> 
Cc: "Nadia Goué" <nadia.goue@uca.fr>, "Mention" <mention@noreply.github.com> 
Envoyé: Jeudi 13 Février 2020 12:42:16 
Objet: Re: [genouest/biomaj2galaxy] error produced by add.py (#2) 



Hi [ https://github.com/nagoue | @nagoue ] 
The 2.1.0 version is finally out now : [ https://pypi.org/project/biomaj2galaxy/2.1.0/ | https://pypi.org/project/biomaj2galaxy/2.1.0/ ] 
Cheers
